// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: like.sql

package db

import (
	"context"
)

const createLike = `-- name: CreateLike :one
INSERT INTO "likes" ("article_id", "user_id")
VALUES ($1, $2) RETURNING id, article_id, user_id
`

type CreateLikeParams struct {
	ArticleID int32 `json:"article_id"`
	UserID    int32 `json:"user_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, createLike, arg.ArticleID, arg.UserID)
	var i Like
	err := row.Scan(&i.ID, &i.ArticleID, &i.UserID)
	return i, err
}
