// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountArticleViewsByArticleId(ctx context.Context, articleID int32) (int64, error)
	CountCategory(ctx context.Context) (int64, error)
	CountTag(ctx context.Context) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateArticleCategory(ctx context.Context, arg CreateArticleCategoryParams) (ArticleCategory, error)
	CreateArticleTag(ctx context.Context, arg CreateArticleTagParams) (ArticleTag, error)
	CreateCategory(ctx context.Context, name string) (Category, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateImage(ctx context.Context, arg CreateImageParams) (Image, error)
	CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateView(ctx context.Context, arg CreateViewParams) error
	FindCategory(ctx context.Context, id int32) (Category, error)
	FindTag(ctx context.Context, id int32) (Tag, error)
	GetArticle(ctx context.Context, id int32) (Article, error)
	GetArticleCategoryByArticleId(ctx context.Context, articleID int32) ([]GetArticleCategoryByArticleIdRow, error)
	GetArticleTagByArticleId(ctx context.Context, articleID int32) ([]GetArticleTagByArticleIdRow, error)
	GetArticles(ctx context.Context, arg GetArticlesParams) ([]GetArticlesRow, error)
	GetImageByArticleId(ctx context.Context, articleID int32) ([]Image, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
